id: AE8908CF9
title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the Liberational
  Life of the Omniscient Jamyang Khyentse Wangpo'
type: translation
pechas:
- I071EF451
- IFFFBF96F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:45.194549
  last_modified_at: 2023-01-04 12:01:45.194553
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I071EF451/1B43: 4E7A
  IFFFBF96F/7849: 4E7A
